NubeIO/rubix-point-server

src/models/point/model_point_store.py
src/source_drivers/modbus/services/modbus_functions/polling/poll.py
src/source_drivers/modbus/services/rtu_polling.py
src/source_drivers/modbus/services/tcp_polling.py

for standard testing db size on RC (with `tests/rest/req_simple.py`)
DB update time went from 
- **avg 800-900ms**
down to 
- **avg 300-400ms**
includes only update on COV

improved polling updates to db

---

src/models/wires/model_wires_plat.py
src/resources/resource_device.py
src/resources/resource_network.py
src/resources/resource_point.py
src/resources/resource_wires_plat.py
src/resources/rest_schema/schema_wires_plat.py
src/resources/utils.py
src/routes.py
src/source_drivers/modbus/resources/device/device_base.py
src/source_drivers/modbus/resources/network/network_base.py
src/source_drivers/modbus/resources/point/point_base.py
tests/resource/test_utils.py

@RaiBnod please update as below
We need to only store max 1 record for this end point
So we need POST then PUT to update
HTTP POST
/api/wires/plat
HTTP DELETE (we dont need to pass in the UUID as there is only meant to be 1 record kept in the `db`)
/api/wires/plat
```
{
"device_id": "device_id",
"device_name": "device_namey",
"client_id": "client_id",
"client_name": "client_name",
"site_id": "site_id",
"site_name": "site_name hey",
"site_address": "site_address",
"site_city": "site_city hey",
"site_state": "site_state hey",
"site_zip": "site_zip hey",
"site_country": "site_country hey",
"site_lat": "site_lat hey",
"site_lon": "site_lon hey"
}
```

added wires-plat endpoint

---

src/routes.py
src/system/resources/memory.py
src/system/resources/systemctl_services.py

0.0.0.0:1515/api/system/service/check
```
{
"service": "mosquitto"
}
```
0.0.0.0:1515/api/system/service/command
```
{
"action": "start",
"service": "mosquitto"
}
```

added services for start/top wires, wires-plat

---

README.md
src/services/mqtt_client/mqtt_client.py

Added more detail to the MQTT topic
Like device/network name

add more detail to mqtt topic

---

.gitignore
src/source_drivers/modbus/resources/device/device_base.py
src/source_drivers/modbus/resources/device/device_singular.py
src/source_drivers/modbus/resources/network/network_singular.py
src/source_drivers/modbus/resources/point/point_singular.py

- Added the `PATCH` API endpoints for editing `network`, `device` and `point`. Please have this postman link for APIs under `Modbus` foler (https://www.getpostman.com/collections/89824c068c774e5e19bb).

Add PATCH API endpoints

---

requirements.txt
src/__init__.py
src/background.py
src/source_drivers/modbus/services/modbus_functions/polling/poll.py
systemd/nubeio-bac-rest.service

Resolves: #97
Resolves: #74
- Background tasks were independent to the `Flask App`, hence `gunicorn` run were ignoring background tasks. Now we have included them on here.

Make Background tasks works on Gunicorn run

---

src/__init__.py

threading fix for use with gunicorn and werkzeug

gunicorn and werkzeug fix

---

README.md
script.bash
systemd/nubeio-bac-rest.service

- A script and `README` edition for running it on production

Add lib_dir parameter of starting gunicorn

---

tests/modbus/r-io-10-init.py

Help:
```
python r-io-10-init.py -h
```
default:
```
python r-io-10-init.py PORT BAUD ADDRESS
python r-io-10-init.py /dev/ttyUSB0 9600 1
```
writing:
```
python r-io-10-init.py /dev/ttyUSB0 9600 1 --uo-writes 1 12 --do-writes 0 1 --uo-configs 1 2 --ui-configs 3
```

Temporary R-IO-10 init script

---

src/event_dispatcher.py
src/interfaces/point.py
src/models/point/model_point.py
src/models/point/model_point_store.py
src/models/point/model_point_store_history.py
src/resources/rest_schema/schema_point.py
src/services/histories/sync/influxdb.py
src/services/mqtt_client/mqtt_client.py
src/source_drivers/modbus/interfaces/point/points.py
src/source_drivers/modbus/models/device.py
src/source_drivers/modbus/models/network.py
src/source_drivers/modbus/models/point.py
src/source_drivers/modbus/resources/point/point_base.py
src/source_drivers/modbus/resources/point/point_singular.py
src/source_drivers/modbus/resources/rest_schema/schema_modbus_device.py
src/source_drivers/modbus/resources/rest_schema/schema_modbus_network.py
src/source_drivers/modbus/resources/rest_schema/schema_modbus_point.py
src/source_drivers/modbus/services/__init__.py
src/source_drivers/modbus/services/modbus_functions/polling/poll.py
src/source_drivers/modbus/services/rtu_polling.py
src/source_drivers/modbus/services/tcp_polling.py

Resolves: #129
Ticket wise steps are carried out.

Add math function and do calculations

---

src/background.py
src/services/mqtt_client/mqtt_client.py
src/system/resources/ping.py

Fix breaking issue of /system/ping

---

config/config.example.json
src/background.py
src/services/histories/point_store_history_cleaner.py
src/services/histories/sync/influxdb.py
src/services/mqtt_client/mqtt_client.py
src/services/mqtt_client/mqtt_client_base.py
src/source_drivers/generic/services/generic_point_listener.py

- fix mqtt
- revert logging changes

mqtt fix and logging revert

---

src/models/device/model_device_mixin.py
src/models/network/model_network_mixin.py
src/models/point/model_point.py
src/models/point/model_point_mixin.py
src/models/point/model_point_store.py
src/models/point/model_point_store_history.py
src/services/histories/history_local.py
src/services/histories/point_store_history_cleaner.py
src/services/histories/sync/influxdb.py
src/source_drivers/modbus/services/modbus_functions/polling/poll.py
src/utils/model_utils.py

Resolves: #186
- Field `ts` related issue fix (converted into `ts_value`, `ts_fault`)
- InfluxDB update issue fix
- Improvements on code

Fix: timestamp related issue fix

---

src/models/point/model_point.py
src/resources/resource_point.py
src/routes.py
src/source_drivers/generic/resources/point/point_value_writer.py
src/source_drivers/generic/services/generic_point_listener.py

- PATCH generic value support via names
- `PATCH`: `/api/generic/points/<string:uuid>/value` to `/api/generic/points_value/uuid/<string:uuid>`
- `PATCH`: `/api/generic/points_value/name/<string:network_name>/<string:device_name>/<string:point_name>`
Postman collection: https://www.getpostman.com/collections/59b9c3ecf3dd5a350f7b

PATCH generic value support via names

---

src/handlers/exception.py
src/services/histories/history_local.py
src/services/histories/point_store_history_cleaner.py
src/services/histories/sync/influxdb.py
src/setting.py
src/source_drivers/generic/services/generic_point_listener.py
src/source_drivers/modbus/services/modbus_polling.py

- Exception decorator creation of handling runtime crashes

Exception handler for loops

---

src/background.py
src/services/histories/point_store_history_cleaner.py
src/setting.py

- Add config to control PointStoreHistoryCleaner cleaning job execution.

PointStoreHistoryCleaner frequency config

---

src/models/point/model_point.py
src/models/point/model_point_store.py
src/source_drivers/generic/models/point.py
src/source_drivers/generic/models/priority_array.py
src/source_drivers/generic/resources/point/point_base.py
src/source_drivers/generic/resources/point/point_value_writer.py
src/source_drivers/generic/resources/rest_schema/schema_generic_point.py
src/source_drivers/generic/services/generic_point_listener.py

Resolves: #158
-  Added new table "priority_array"
-  Modified "update_point_store" to update priority_array and point_store
-  Added "priority_array" and removed "value" and "value_raw" argument  in ```/api/generic/points_value/uuid/<uuid>``` endpoint:
```
curl -x PATCH http://localhost:1515/api/generic/points_value/uuid/<uuid> -H “Content-Type: application/json” -d
‘{
"fault":<fault>,
"fault_message":<fault_message>,
"priority_array": {
"_1": <_1>,
"_2": <_2>,
"_3": <_3>,
"_4": <_4>,
"_5": <_5>,
"_6": <_6>,
"_7": <_7>,
"_8": <_8>,
"_9": <_9>,
"_10": <_10>,
"_11": <_11>,
"_12": <_12>,
"_13": <_13>,
"_14": <_14>,
"_15": <_15>,
"_16": <_16>
}
}’
```
-  Added "priority_array" and removed "value" and "value_raw"  payload in GenericPointListener

Add Priority Array on Points

---

src/models/point/model_point.py
src/source_drivers/generic/interfaces/point/points.py
src/source_drivers/generic/models/point.py
src/source_drivers/generic/resources/point/point_value_writer.py
src/source_drivers/generic/resources/rest_schema/schema_generic_point.py
src/source_drivers/generic/services/generic_point_listener.py

Resolves: #215
-  Added generic_points > type and unit fields 
-  Added "value_raw" argument  in ```/api/generic/points_value/uuid/<uuid>``` endpoint. Examples:
```
curl -x PATCH http://localhost:1515/api/generic/points_value/uuid/<uuid> -H “Content-Type: application/json” -d
‘{
"priority_array": {
"_1": <_1>,
"_2": <_2>,
"_3": <_3>,
"_4": <_4>,
"_5": <_5>,
"_6": <_6>,
"_7": <_7>,
"_8": <_8>,
"_9": <_9>,
"_10": <_10>,
"_11": <_11>,
"_12": <_12>,
"_13": <_13>,
"_14": <_14>,
"_15": <_15>,
"_16": <_16>
}
}’
curl -x PATCH http://localhost:1515/api/generic/points_value/uuid/<uuid> -H “Content-Type: application/json” -d
‘{
"value_raw": <value_raw>
}’
```
-  Added "value_raw" payload in GenericPointListener

Generic Point support writing string

---

src/source_drivers/modbus/services/modbus_polling.py
src/source_drivers/modbus/services/polling_registry.py
src/system/resources/ping.py

Resolves: #131
- Added polling_stats in endpoint `/api/system/ping`

Add polling stats

---

config/config.example.json
config/logging.example.conf
config/logging.prod.example.conf
poetry.lock
pyproject.toml
src/background.py
src/models/point/model_point_store.py
src/services/histories/sync/influxdb.py
src/services/mqtt_client/mqtt_client_base.py
src/setting.py
src/system/resources/ping.py

- Sync only when `mqtt_rest_bridge_listener.enabled`
- Add bridge details on `/api/system/ping`

Improvement on sync service

---

config/config.example.json
poetry.lock
pyproject.toml
src/__init__.py
src/background.py
src/services/histories/sync/influxdb.py
src/services/histories/sync/postgresql.py
src/setting.py
src/system/resources/ping.py
tests/setting_dump.py

CU-25ch1w[closed]
- Added PostgreSQL history sync

Add postgresql history sync

---

src/models/model_base.py

Resolves: #157
- Added changed flag to inspect changes before publish.

Don't publish on PATCH when nothing changed

---

README.md
src/services/mqtt_client/mqtt_listener.py

- Fix: retain msg clearing issue (points, schedules data were clearing out)

Fix: retain msg clearing issue

---

src/background.py
src/models/model_base.py
src/models/point/model_point_store.py
src/services/mqtt_republish.py

Resolves: #283
- Added MQT republish Model and COV values on app start
- Changed model_point_store update condition: db.func.abs(self.__table__.c.value - self.value) > cov_threshold

Improvement on MQTT

---

src/enums/point.py
src/models/point/model_point.py
src/resources/rest_schema/schema_point.py
src/utils/math_functions.py

Resolves: #292
- Added advanced math function 
- Same as what was done for lora https://github.com/NubeIO/lora-raw/pull/76 & https://github.com/NubeIO/lora-raw/pull/79

Update to points - advanced math

---

src/drivers/generic/resources/point/point_singular.py
src/drivers/modbus/models/point.py
src/drivers/modbus/services/polling/function_utils.py
src/drivers/modbus/services/polling/poll.py
src/models/point/model_point.py
src/models/point/priority_array.py
src/services/mqtt_client/mqtt_listener.py

- Fix: MQTT network retain clear issue
- Fix: ModbusFunctionCode issue (Invalid function code)
- Improvement: generic point priority array write on update

Improvement: miscellaneous

---

src/drivers/modbus/models/point.py
src/drivers/modbus/resources/rest_schema/schema_modbus_point.py
src/drivers/modbus/services/polling/modbus_polling.py

Resolves: #301
- Added write_value_once with type Boolean
- write_value_once is True and  function_code is WRITE_COIL then we will re-write again until we succeed (point_store.fault = False).

On point write dont poll write value again

---

src/models/point/model_point.py

Resolves: #259
- Added validations `input_min <= input_max` and `scale_min <= scale_max`

Add input and scale min,max validation

---

src/services/histories/sync/postgresql.py

Resolves: #315
- Added tables `wires_plats`, `networks`, `modbus_networks`, `devices`, `mobus_devices` in postgres history sync.

Redo tables for postgres

---

src/services/histories/history_local.py

Resolves: #345 
- History interval issue fix

History interval issue fix

---

src/enums/point.py
src/models/point/model_point.py
src/services/histories/history_local.py

Resolves: #324
- Add COV_AND_INTERVAL history type support

Add COV_AND_INTERVAL history type support

---

src/models/point/model_point.py
src/services/mqtt_client/mqtt_client.py

Resolves: #362 
- Added `priority` to MQTT message

Add priority to MQTT message

---

src/drivers/generic/resources/point/point_base.py
src/drivers/modbus/models/point.py
src/drivers/modbus/resources/point/point_base.py
src/models/point/model_point.py
src/models/point/priority_array.py

Resolves: #378
- Fix PATCH: read <> write point switching

Fix PATCH: read <> write point switch 

---

src/drivers/generic/resources/point/point_base.py
src/drivers/modbus/models/point.py
src/drivers/modbus/resources/point/point_base.py
src/models/point/model_point.py

- Remove redundancy of default value

Remove redundancy of default value

---

poetry.lock
pyproject.toml
src/services/histories/sync/influxdb.py
src/services/histories/sync/postgresql.py
src/services/mqtt_client/mqtt_client.py
src/services/mqtt_client/mqtt_listener.py

- Upgrade rubix-registry to v1.1.1 (used TinyDB)

Upgrade rubix-registry to v1.1.1 (used TinyDB)

---

src/services/mqtt_client/mqtt_client.py
src/utils/mqtt_stream_handler.py

Fix: MQTT data push

---

src/services/histories/point_store_history_cleaner.py

Resolves: #434
- Added `filter(PointStoreHistoryModel.id < max_id)` to keep last history

Fix: history cleaner deleting all histories issue

---

src/services/histories/history_local.py

- Fixed app freeze on history local sync interval.

Fix: app freeze on history local sync interval

---

src/services/histories/history_local.py

- Fixed latest point store history on sync interval.

Fix: latest point store history on sync interval
